# Generated by Django 5.1.4 on 2026-07-04 13:57

import ecommercesite.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_configured_price_cartitem_selected_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='client_uploads', validators=[ecommercesite.validators.validate_upload_file]),
        ),
    ]
