# Generated by Django 5.1.4 on 2026-05-17 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_selected_options_orderitem_uploaded_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('file_received', 'Fichier reçu'), ('reviewing', 'En verification'), ('production', 'En production'), ('ready', 'Pret'), ('shipped', 'Expedie'), ('delivered', 'Livre'), ('cancelled', 'Annule')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
