# Generated by Django 5.1.4 on 2026-05-17 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_statuses_and_seed_history(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderStatusHistory = apps.get_model("orders", "OrderStatusHistory")
    status_map = {
        "production": "printing",
        "ready": "packaging",
    }
    for order in Order.objects.all():
        new_status = status_map.get(order.status, order.status)
        if new_status != order.status:
            order.status = new_status
            order.save(update_fields=["status"])
        if not OrderStatusHistory.objects.filter(order=order).exists():
            OrderStatusHistory.objects.create(
                order=order,
                previous_status="",
                new_status=order.status,
                note="Historique initialise pendant la Phase 6.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_checkout_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normale'), ('urgent', 'Urgente')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='production_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='order_proofs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('file_received', 'Fichier reçu'), ('reviewing', 'Verification fichier'), ('client_validation', 'Validation client'), ('printing', 'Impression'), ('finishing', 'Finition'), ('packaging', 'Emballage'), ('shipped', 'Expedie'), ('delivered', 'Livre'), ('cancelled', 'Annule')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statut',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(normalize_statuses_and_seed_history, migrations.RunPython.noop),
    ]
