# Generated by Django 5.1.4 on 2026-07-04 13:57

import ecommercesite.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_status_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='order_proofs', validators=[ecommercesite.validators.validate_upload_file]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='order_uploads', validators=[ecommercesite.validators.validate_upload_file]),
        ),
    ]
