# Generated by Django 5.1.4 on 2026-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_proof_file_alter_orderitem_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('file_received', 'Fichier recu'), ('reviewing', 'Verification fichier'), ('client_validation', 'Validation client'), ('printing', 'Impression'), ('finishing', 'Finition'), ('packaging', 'Emballage'), ('shipped', 'Expedie'), ('delivered', 'Livre'), ('cancelled', 'Annule')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('file_received', 'Fichier recu'), ('reviewing', 'Verification fichier'), ('client_validation', 'Validation client'), ('printing', 'Impression'), ('finishing', 'Finition'), ('packaging', 'Emballage'), ('shipped', 'Expedie'), ('delivered', 'Livre'), ('cancelled', 'Annule')], max_length=30),
        ),
    ]
