# Generated by Django 5.1.4 on 2026-07-04 13:57

import ecommercesite.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='quote_uploads', validators=[ecommercesite.validators.validate_upload_file]),
        ),
    ]
