# Generated by Codex on 2026-10-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_contactrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactRequest",
        ),
    ]
