# Generated by Django 5.1.4 on 2026-07-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contactrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
