# Generated by Django 5.1.4 on 2026-08-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_contactrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'catégories'},
        ),
    ]
